excercise_search_payload = {'Type_Cardio': '0',
'Type_Strength': '0',
'Type_Stretching': '0',
'BodyPart_Abdominals': '0',
'BodyPart_Biceps': '0',
'BodyPart_Chest': '0',
'BodyPart_Forearms': '0',
'BodyPart_Neck': '0',
'BodyPart_Shoulders': '0',
'BodyPart_Triceps': '0',
'Level_Beginner': '0',
'Level_Expert': '0',
'Level_Intermediate': '0',
'Equipment_Gym': '0',
'Equipment_Body_Only': '0',
'BodyPart_Legs': '0',
'BodyPart_Back': '0',
'BodyPart_FullBody': '0'}


diet_search_payload = {'Calories': '500',
'FatContent': '20',
'SaturatedFatContent': '5',
'CholesterolContent': '30',
'SodiumContent': '200',
'CarbohydrateContent': '50',
'FiberContent': '4',
'SugarContent': '8',
'ProteinContent': '25',
'Allergies': 'ginger',
'MaxTime': '30'}